name: Build APK with Docker

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build APK in Docker
      run: |
        docker run --rm -v $PWD:/app kivy/buildozer:python3.10 \
          buildozer -v android debug
