name: Build APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y \
          zlib1g-dev libncurses-dev libffi-dev libssl-dev libsqlite3-dev libjpeg-dev \
          build-essential unzip openjdk-17-jdk git curl

    - name: Install pip dependencies
      run: pip install --upgrade pip && pip install buildozer cython

    - name: Install Android cmdline-tools and SDK packages
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip -q commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"
        yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=$HOME/android-sdk" >> $GITHUB_ENV
        echo "ANDROIDNDK=$HOME/android-sdk/ndk/25.2.9519653" >> $GITHUB_ENV
        echo "PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$HOME/android-sdk/platform-tools:$PATH" >> $GITHUB_ENV

    - name: Build APK
      env:
        ANDROIDSDK: ${{ env.ANDROIDSDK }}
        ANDROIDNDK: ${{ env.ANDROIDNDK }}
      run: |
        buildozer android debug

    - name: Install Android build-tools for Buildozer
      run: |
        mkdir -p $HOME/.buildozer/android/platform/android-sdk
        ln -s $HOME/android-sdk/cmdline-tools/latest $HOME/.buildozer/android/platform/android-sdk/build-tools
        yes | sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk "build-tools;33.0.2" "platform-tools" "platforms;android-33"
        yes | sdkmanager --sdk_root=$HOME/.buildozer/android/platform/android-sdk --licenses
