name: Build PyShieldMobile

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install system dependencies
      run: |
    - name: Install Android cmdline-tools
      run: |
        mkdir -p $HOME/android-sdk/cmdline-tools
        curl -o commandlinetools.zip https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip
        unzip commandlinetools.zip -d $HOME/android-sdk/cmdline-tools
        mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
        export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
        yes | sdkmanager --sdk_root=$HOME/android-sdk \"platform-tools\" \"platforms;android-33\" \"build-tools;33.0.2\" \"ndk;25.2.9519653\"

        sudo apt-get update
        sudo apt-get install -y zlib1g-dev libncurses-dev libffi-dev libssl-dev libsqlite3-dev libjpeg-dev build-essential unzip openjdk-17-jdk

    - name: Install pip dependencies
      run: pip install buildozer

    - name: Install Android SDK
        mkdir -p $HOME/android-sdk
        yes | sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

    - name: Set environment variables
      run: |
        echo "ANDROIDSDK=$HOME/android-sdk" >> 
        echo "ANDROIDNDK=$HOME/android-sdk/ndk/25.2.9519653" >> 

    - name: Build APK
      run: |
        export ANDROIDSDK=$HOME/android-sdk
        export ANDROIDNDK=$HOME/android-sdk/ndk/25.2.9519653
        buildozer android debug
